import type { Entity } from '../store/useSynqStore'
import { getGenerationOrder } from './dataGenerator'

/**
 * Triggers a browser file download using a generated URL Blob.
 */
function triggerFileDownload(content: string, fileName: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.setAttribute('href', url)
  link.setAttribute('download', fileName)
  link.style.visibility = 'hidden'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Exports data object to JSON format.
 */
export function exportToJSON(data: any, fileName: string) {
  const content = JSON.stringify(data, null, 2)
  triggerFileDownload(content, fileName, 'application/json;charset=utf-8;')
}

/**
 * Helper to escape and format a cell value for CSV formatting.
 */
function formatCSVCell(value: any): string {
  if (value === null || value === undefined) return ''
  
  let stringVal = ''
  if (typeof value === 'object') {
    stringVal = JSON.stringify(value)
  } else {
    stringVal = String(value)
  }

  // If the value contains quotes, commas, or newlines, escape quotes by doubling them and wrap in double quotes
  if (stringVal.includes('"') || stringVal.includes(',') || stringVal.includes('\n') || stringVal.includes('\r')) {
    return `"${stringVal.replace(/"/g, '""')}"`
  }

  return stringVal
}

/**
 * Exports columns and rows to CSV format.
 */
export function exportToCSV(headers: string[], rows: any[], fileName: string) {
  const headerLine = headers.join(',')
  const rowLines = rows.map((row) => 
    headers.map((header) => formatCSVCell(row[header])).join(',')
  )

  const csvContent = [headerLine, ...rowLines].join('\n')
  triggerFileDownload(csvContent, fileName, 'text/csv;charset=utf-8;')
}

/**
 * Formats a javascript value into SQL value representation.
 */
function formatSQLValue(value: any, type: string): string {
  if (value === null || value === undefined) {
    return 'NULL'
  }

  switch (type) {
    case 'number':
    case 'currency':
      if (typeof value === 'number' && !isNaN(value)) {
        return String(value)
      }
      const parsedNum = parseFloat(value)
      return isNaN(parsedNum) ? 'NULL' : String(parsedNum)

    case 'boolean':
      return value ? 'TRUE' : 'FALSE'

    case 'uuid':
    case 'email':
    case 'date':
    case 'enum':
    case 'foreign_key':
    case 'string':
    default:
      // Double the single quotes to escape them in SQL string literal
      const escaped = String(value).replace(/'/g, "''")
      return `'${escaped}'`
  }
}

/**
 * Exports generated data to a SQL file containing ordered INSERT statements.
 * It uses topological sorting (getGenerationOrder) to prevent foreign key errors.
 */
export function exportToSQL(
  entities: Entity[],
  generatedData: Record<string, any[]>,
  fileName: string
) {
  // 1. Resolve tables in dependency order
  const orderedEntities = getGenerationOrder(entities)
  const sqlStatements: string[] = []

  sqlStatements.push('-- Generated by Synq Relational Synthetic Data Engine')
  sqlStatements.push(`-- Exported on: ${new Date().toISOString()}`)
  sqlStatements.push('')

  for (const entity of orderedEntities) {
    const rows = generatedData[entity.id] || []
    if (rows.length === 0) continue

    // Columns: ID + other configured field names
    const columns = ['id', ...entity.fields.map((f) => f.name)]
    const tableName = entity.name.toLowerCase()

    sqlStatements.push(`-- Table: ${tableName}`)

    // Split SQL inserts into chunks of 500 rows for query limits safety
    const chunkSize = 500
    for (let i = 0; i < rows.length; i += chunkSize) {
      const chunkRows = rows.slice(i, i + chunkSize)
      
      const insertHeader = `INSERT INTO ${tableName} (${columns.join(', ')}) VALUES`
      const valuesLines = chunkRows.map((row) => {
        const fieldValues = columns.map((colName) => {
          if (colName === 'id') {
            return formatSQLValue(row.id, 'uuid')
          }
          const field = entity.fields.find((f) => f.name === colName)
          const fieldType = field?.type || 'string'
          return formatSQLValue(row[colName], fieldType)
        })
        return `  (${fieldValues.join(', ')})`
      })

      sqlStatements.push(`${insertHeader}\n${valuesLines.join(',\n')};`)
    }
    sqlStatements.push('')
  }

  triggerFileDownload(sqlStatements.join('\n'), fileName, 'text/plain;charset=utf-8;')
}
