import type { Entity, SchemaField } from '../store/useSynqStore'
import { getGenerationOrder } from './schemaGraph'

/**
 * Generates TypeScript interface declarations from a schema, so a consumer of
 * the mock API can type its responses. Faker-free, like schemaGraph, so it
 * stays out of the generator's lazy-loaded chunk.
 */

/** `order_items` / `order items` / `orderItems` -> `OrderItem`. */
export function toPascalCase(name: string): string {
  const words = name
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)

  if (words.length === 0) return 'Entity'

  const pascal = words
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('')

  // A leading digit is not a valid identifier start.
  return /^[0-9]/.test(pascal) ? `Entity${pascal}` : pascal
}

/** Quotes a property name only when it isn't a valid bare identifier. */
function propertyKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name)
}

/** Maps a schema field to its TypeScript type expression. */
export function fieldToTsType(field: SchemaField): string {
  switch (field.type) {
    case 'number':
    case 'currency':
      return 'number'

    case 'boolean':
      return 'boolean'

    case 'enum':
      // A union of literals is more useful than a bare string.
      if (field.options && field.options.length > 0) {
        return field.options.map((option) => JSON.stringify(option)).join(' | ')
      }
      return 'string'

    case 'uuid':
    case 'email':
    case 'date':
    case 'foreign_key':
    case 'string':
    default:
      return 'string'
  }
}

/** Builds the declaration for a single entity. */
export function entityToInterface(entity: Entity, entities: Entity[]): string {
  const lines: string[] = [`export interface ${toPascalCase(entity.name)} {`]

  // Every generated record carries a uuid primary key.
  lines.push('  id: string;')

  for (const field of entity.fields) {
    const comments: string[] = []

    if (field.type === 'foreign_key') {
      const target = entities.find((e) => e.id === field.referenceEntityId)
      comments.push(target ? `FK -> ${toPascalCase(target.name)}.id` : 'FK -> (deleted entity)')
    }
    if (field.pattern) comments.push(`matches /${field.pattern}/`)

    const comment = comments.length > 0 ? ` // ${comments.join(', ')}` : ''
    lines.push(`  ${propertyKey(field.name)}: ${fieldToTsType(field)};${comment}`)
  }

  lines.push('}')
  return lines.join('\n')
}

/**
 * Renders the whole schema as a .ts module. Entities are emitted in dependency
 * order so a referenced interface is declared before the one referencing it.
 */
export function generateTypeScriptInterfaces(entities: Entity[]): string {
  if (entities.length === 0) {
    return '// No entities defined in this schema.\n'
  }

  const header = [
    '// Generated by Synq — Serverless Synthetic Data Engine',
    `// ${new Date().toISOString()}`,
    ''
  ]

  // A circular schema can't be topologically sorted; declaration order doesn't
  // affect TypeScript interfaces, so fall back to the given order rather than
  // failing the export.
  let ordered: Entity[]
  try {
    ordered = getGenerationOrder(entities)
  } catch {
    ordered = entities
  }

  const blocks = ordered.map((entity) => entityToInterface(entity, entities))
  return `${header.join('\n')}${blocks.join('\n\n')}\n`
}
